# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'repowidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RepoWidget(object):
    def setupUi(self, RepoWidget):
        RepoWidget.setObjectName("RepoWidget")
        RepoWidget.resize(552, 353)
        self.gridLayout = QtWidgets.QGridLayout(RepoWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_repo_save = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_save.setText("")
        icon = QtGui.QIcon.fromTheme("document-save")
        self.pb_repo_save.setIcon(icon)
        self.pb_repo_save.setObjectName("pb_repo_save")
        self.gridLayout.addWidget(self.pb_repo_save, 1, 1, 1, 1)
        self.pb_repo_add = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_add.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pb_repo_add.setIcon(icon)
        self.pb_repo_add.setObjectName("pb_repo_add")
        self.gridLayout.addWidget(self.pb_repo_add, 2, 1, 1, 1)
        self.pb_repo_open = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_open.setText("")
        icon = QtGui.QIcon.fromTheme("document-open")
        self.pb_repo_open.setIcon(icon)
        self.pb_repo_open.setObjectName("pb_repo_open")
        self.gridLayout.addWidget(self.pb_repo_open, 0, 1, 1, 1)
        self.pb_repo_remove = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_remove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove-symbolic")
        self.pb_repo_remove.setIcon(icon)
        self.pb_repo_remove.setObjectName("pb_repo_remove")
        self.gridLayout.addWidget(self.pb_repo_remove, 3, 1, 1, 1)
        self.pb_repo_up = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_up.setText("")
        icon = QtGui.QIcon.fromTheme("arrow-up")
        self.pb_repo_up.setIcon(icon)
        self.pb_repo_up.setObjectName("pb_repo_up")
        self.gridLayout.addWidget(self.pb_repo_up, 4, 1, 1, 1)
        self.tw_repo = QtWidgets.QTableWidget(RepoWidget)
        self.tw_repo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_repo.setObjectName("tw_repo")
        self.tw_repo.setColumnCount(2)
        self.tw_repo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_repo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_repo.setHorizontalHeaderItem(1, item)
        self.tw_repo.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tw_repo, 0, 0, 7, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.pb_repo_down = QtWidgets.QPushButton(RepoWidget)
        self.pb_repo_down.setText("")
        icon = QtGui.QIcon.fromTheme("arrow-down")
        self.pb_repo_down.setIcon(icon)
        self.pb_repo_down.setObjectName("pb_repo_down")
        self.gridLayout.addWidget(self.pb_repo_down, 5, 1, 1, 1)

        self.retranslateUi(RepoWidget)
        QtCore.QMetaObject.connectSlotsByName(RepoWidget)

    def retranslateUi(self, RepoWidget):
        _translate = QtCore.QCoreApplication.translate
        RepoWidget.setWindowTitle(_translate("RepoWidget", "Form"))
        item = self.tw_repo.horizontalHeaderItem(0)
        item.setText(_translate("RepoWidget", "Name"))
        item = self.tw_repo.horizontalHeaderItem(1)
        item.setText(_translate("RepoWidget", "Address"))
